version = 0.1

[default.deploy.parameters]
stack_name = "task-management-system"
resolve_s3 = true
s3_prefix = "jeevan-taskmanager-dev-20251019"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
